relayprotocol/relay-vaults

smart-contracts/contracts/RelayBridge.sol, smart-contracts/contracts/RelayPool.sol, smart-contracts/contracts/Types.sol, smart-contracts/test/RelayPool/claim.hardhat.ts, smart-contracts/test/RelayPool/curator.hardhat.ts, smart-contracts/test/RelayPool/fees.hardhat.ts, smart-contracts/test/RelayPool/hyperlane.hardhat.ts
Adding a cool down period by origin.
https://github.com/unlock-protocol/relay-protocol/issues/95
=> Adding a cool down period by origin

backend/package.json, backend/ponder.config.ts, yarn.lock
This PR introduces updates to the backend service configuration.
=> feature(backend): Update and sync config

smart-contracts/test/RelayPool/morpho-yield-pool.ethereum.ts
=> fix(smart-contracts): bring back morpho tests

backend/src/handlers/RelayPool/OutstandingDebtChanged.ts, backend/src/index.ts
This PR introduces a handler for the `OutstandingDebtChanged` event.
=> feature(backend): `OutstandingDebtChanged` event handler

claimer/main.ts, packages/client/src/queries/index.ts
This PR introduces a fix for the claimer job to ensure it properly retrieves bridge transactions.
=> fix(claimer): Properly retrieve bridge transactions

claimer/main.ts, claimer/src/prove-transactions.ts, claimer/src/runner.ts, claimer/src/util/retrieve-schema.ts
This PR introduces a fix for the `claimer` script to ensure it correctly retrieves the intended database schema. This resolves issues where the script was referencing an incorrect or outdated schema, leading to potential data mismatches or errors.
=> fix(claimer): Utilise correct schema

backend/ponder.schema.ts, backend/src/intervals/VaultSnapshot.ts
This PR introduces the yield pool’s share price to the snapshot data, providing more visibility into the underlying asset’s value.
=> feature(backend): Include yield pool share price in snapshot

backend/ponder.schema.ts, backend/src/handlers/RelayPool/LoanEmitted.ts, backend/src/handlers/RelayPoolFactory/PoolDeployed.ts
This PR introduces total fee tracking for relay pools.
=> feature(backend): Add `totalBridgeFees` for pools

backend/src/handlers/RelayPool/LoanEmitted.ts
This PR introduces proper indexing for a pool’s `totalBridgeFees`, ensuring accurate tracking and retrieval. This fixes potential retrieval inconsistencies.
=> feature(backend): Properly index pool’s `totalBridgeFees`

backend/ponder.schema.ts, backend/src/handlers/RelayPool/OriginAdded.ts, backend/src/handlers/RelayPool/OutstandingDebtChanged.ts
This PR introduces indexing for the outstanding debt associated with a pool’s origins.
=> feature(backend): Index outstandingDebt for pool origins

backend/package.json, backend/ponder.config.ts, package.json, packages/addresses/eslint.config.js, packages/addresses/package.json, packages/addresses/src/index.ts, packages/addresses/tsconfig.json, smart-contracts/package.json, smart-contracts/tasks/deploy/pool.ts, smart-contracts/tasks/deploy/relay-bridge.ts, smart-contracts/tasks/origins/add.ts, yarn.lock
This is to avoid copying and pasting addresses over and over :)
=> feat: adding an addresses package

backend/src/handlers/RelayPool/Deposit.ts, backend/src/handlers/RelayPool/LoanEmitted.ts, backend/src/handlers/RelayPool/OutstandingDebtChanged.ts, backend/src/handlers/RelayPool/Withdraw.ts
This PR introduces updates to the handlers to correctly use composite keys when updating pools.
=> fix(backend): Properly handle composite keys when updating pools

backend/ponder.config.ts, backend/ponder.schema.ts, backend/src/handlers/RelayPool/Deposit.ts, backend/src/handlers/RelayPool/Withdraw.ts, backend/src/index.ts
Ponder/Drizzle manages that for us.
=> Removed composite keys

smart-contracts/package.json
https://github.com/relayprotocol/relay-protocol/issues/170
=> not running sepolia tests for now

smart-contracts/contracts/RelayPool.sol, smart-contracts/test/RelayPool/asset-transfer.hardhat.ts
Streaming duration is not fully reset when a new deposit is made, but extended proportionnaly based on how much remains to be streamed
=> Adjust streaming duration

smart-contracts/contracts/RelayPool.sol, smart-contracts/test/RelayPool/hyperlane.hardhat.ts
This should simplify things on the backend!
=> outstanding debt events include origin

smart-contracts/contracts/RelayPoolNativeGateway.sol, smart-contracts/test/RelayPool/native-gateway.ethereum.ts
fix https://github.com/relayprotocol/relay-protocol/issues/115
=> feat(smart-contracts): pass pool as param in native gateway

smart-contracts/contracts/RelayPool.sol, smart-contracts/test/RelayPool/swap-and-deposit.ethereum.ts
fix https://github.com/relayprotocol/relay-protocol/issues/156
=> fix(smart-contracts): make `swapAndDeposit` `onlyOwner` 

packages/networks/package.json
=> Bump package version

smart-contracts/contracts/RelayPoolNativeGateway.sol, smart-contracts/contracts/utils/tests/SelfDestructible.sol, smart-contracts/test/RelayPool/native-gateway.ethereum.ts
use soft balance check in native gateway to prevent possible DoS attack by sending value to the contract https://cantina.xyz/code/bdc0388a-3785-49cd-b2e8-71ce6acd2d9d/findings/6
=> fix(smart-contracts): use soft balance checks in native gateway

smart-contracts/contracts/TokenSwap.sol
remove duplicate approval to improve gas efficiency of the swap function
=> remove permit2 approval

smart-contracts/contracts/RelayPool.sol, smart-contracts/test/RelayPool/fees.hardhat.ts, smart-contracts/test/RelayPool/hyperlane.hardhat.ts
A simple change to make our lives easier... This does not change the APIs
=> adding chainId and bridge in OriginSettings

backend/.gitignore, backend/generated/schema.graphql, backend/ponder.schema.ts, backend/src/handlers/OPPortal/WithdrawalFinalized.ts, backend/src/handlers/RelayBridge/BridgeInitiated.ts, backend/src/handlers/Zksync/WithdrawalFinalized.ts, backend/src/index.ts, packages/helpers/src/abis/index.ts, packages/helpers/src/abis/zksync/IL1SharedBridge.json, packages/helpers/src/abis/zksync/IL2SharedBridge.json, smart-contracts/tasks/bridge.ts
This will index all `WithdrawalFinalized` events emitted when using native withdrawals from Relay pools
=> feat(backend): indexing finalized withdrawals from native bridges

smart-contracts/ignition/deployments/bridges/2741/0x4119dde0d4136ac43fd5f0e53f9ac47dc8922b11/params.json
@clemsos It looks like you did not commit this file?
=> adding missing file

smart-contracts/tasks/deploy/bridge-proxy.ts, smart-contracts/test/BridgeProxy/CCTPBridgeProxy.optimism.ts, smart-contracts/test/BridgeProxy/OPStackNativeBridgeProxy.base.ts, smart-contracts/test/BridgeProxy/OPStackNativeBridgeProxy.optimism.ts, smart-contracts/test/BridgeProxy/ZkSyncBridgeProxy.zksync.ts, smart-contracts/test/BridgeProxy/claim-native.hardhat.ts
For some reason the types PR was passing... even though it broke tests in smart contracts :/
=> fixing types

.github/workflows/pr.yml
per docs here https://github.com/tj-actions/changed-files/blob/9934ab3fdf63239da75d9e0fbd339c48620c72c4/action.yml#L305C3-L306
=> ci: include file deletion while checking for file changes

packages/networks/src/networks/bob.ts, packages/networks/src/networks/echos.ts, packages/networks/src/networks/hemi.ts, packages/networks/src/networks/index.ts, packages/networks/src/networks/rari.ts, packages/networks/src/networks/swell.ts, packages/networks/src/networks/swellchain.ts
This adds support for 
- BOB (60808)
- Swellchain (1923)
- Hemi (43111)
- Rari (1380012617)
=> networks: add some more chains

backend/src/handlers/RelayBridgeFactory/BridgeDeployed.ts, backend/src/handlers/RelayPool/Deposit.ts, backend/src/handlers/RelayPool/Withdraw.ts, backend/src/handlers/RelayPoolFactory/PoolDeployed.ts, backend/src/intervals/VaultSnapshot.ts
When a re-org happens it can create a conflict in the database
=> better handling of reorgs

smart-contracts/tasks/deploy/bridge-proxy.ts
Some additional safety checks to make sure settings are correct across chains when deploying
=> add deployment checks

bin/entrypoint.sh
useful to pass command args when running the backend
=> pass all args to Docker entrypoint

packages/abis/package.json
so we can loop through them all at runtime
=> abis: copy versions files to dist

Dockerfile, backend/README.md, backend/railway.json, smart-contracts/README.md
Cleaning up Railway docs & config
=> no more railway

packages/client/src/queries.graphql, packages/client/src/services/vault.ts
This PR introduces improvements and updated queries to the vaults' `client` package.
=> Improved `client` package

packages/networks/src/networks/arbitrum.ts, packages/networks/src/networks/base.ts, packages/networks/src/networks/ethereum.ts, packages/types/src/types/networks.ts
Getting ready to deploy the vaults on these chains!
=> adding base and arbitrum as VaultNetworkConfig

.github/workflows/release.yml
to generate app key - [source](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow) and [here](https://github.com/actions/create-github-app-token/tree/main?tab=readme-ov-file#configure-git-cli-for-an-apps-bot-user)
=> use official actions from Github

backend/src/intervals/PoolSnapshot.ts
The fees are only taken into account for the `totalAssets` once the bridge "resolves", which creates a period where it "looks" like the vault is generating no fees. This PR fixes that.
=> using the pendingBridgeFees in the calculation of APY

Dockerfile
https://ponder.sh/docs/advanced/telemetry#telemetry
=> disable ponder telemetry

backend/generated/schema.graphql, backend/ponder.schema.ts, backend/src/handlers/OPPortal/WithdrawalFinalized.ts, backend/src/handlers/OPPortal/WithdrawalProven.ts, backend/src/handlers/OrbitOutbox/OutBoxTransactionExecuted.ts, backend/src/handlers/PoolSnapshot.ts, backend/src/handlers/RelayBridge/BridgeInitiated.ts, backend/src/handlers/RelayBridgeFactory/BridgeDeployed.ts, backend/src/handlers/RelayPool/Deposit.ts, backend/src/handlers/RelayPool/LoanEmitted.ts, backend/src/handlers/RelayPool/OriginAdded.ts, backend/src/handlers/RelayPool/OutstandingDebtChanged.ts, backend/src/handlers/RelayPool/OwnershipTransferred.ts, backend/src/handlers/RelayPool/Transfer.ts, backend/src/handlers/RelayPool/Withdraw.ts, backend/src/handlers/RelayPool/YieldPoolChanged.ts, backend/src/handlers/RelayPoolFactory/PoolDeployed.ts, backend/src/handlers/RelayPoolTimelock/RoleGranted.ts, backend/src/handlers/RelayPoolTimelock/RoleRevoked.ts, backend/src/handlers/Zksync/BridgeMint.ts
they are required to be able to export data for viz in Hex
=> backend: add `created_at` and `updated_at` fields

backend/package.json
add a `vaults-view` pg view (virtual table) to simplify 3rd party request on indexed data
https://ponder.sh/docs/production/self-hosting#views-pattern
=> backend: add pg view

packages/networks/src/networks/bob.ts
they upgraded to bedrock recently using https://github.com/risc0/kailua
=> BOB new dispute game contract

backend/src/logger.ts
preventing from cluttering datadog logs
=> backend: log only realtime events

smart-contracts/tasks/deploy/bridge-proxy.ts, smart-contracts/tasks/origins/add.ts
We are starting to have quite a bunch of networks there so makes it easier to look one up
=> sort networks in alphabetical order on contracts cli

packages/helpers/src/arb.ts, smart-contracts/contracts/BridgeProxy/deposit/ArbitrumOrbitNativeDepositBridgeProxy.sol, smart-contracts/tasks/bridge.ts, smart-contracts/test/BridgeProxy/deposit/ArbitrumOrbitNativeDepositBridgeProxy.ethereum.ts
Fix calculations for Arb retryable tickets cost  + prevent the entire value to be used by the ticket (leave the hyperlane fee intact)
=> eth > arb bridge fix amount

smart-contracts/lib/multisig.ts
The new SAFE package requires a few changes...
=> updated SAFE API
