relayprotocol/relay-vaults

- smart-contracts/contracts/RelayPool.sol
- smart-contracts/test/RelayPool/claim.hardhat.ts
- smart-contracts/test/RelayPool/curator.hardhat.ts
- smart-contracts/test/RelayPool/fees.hardhat.ts
- smart-contracts/test/RelayPool/hyperlane.hardhat.ts
For this, we cannot use the pool's curator because this may need to be very fast and the curator should be a timelock.
https://github.com/unlock-protocol/relay-protocol/issues/96
> Adding a mechanism to disable an origin

- backend/package.json
- backend/src/api/index.ts
- yarn.lock
This PR introduces an upgrade to `ponder` `v0.9.2`, and addressing breaking changes.
> Upgrade `ponder` to `v0.9.2`

- backend/src/handlers/RelayPool/OriginAdded.ts
- backend/src/index.ts
This PR introduces indexing support for the `OriginAdded` event in `RelayPool`, allowing tracking of new origins added post-deployment.
> feature(backend): Index `OriginEvent` event in `RelayPool`

- smart-contracts/package.json
- smart-contracts/tasks/utils/exportAbis.ts
- yarn.lock
we remove semver that was used for bumping version of the abi packages to prepare a future use of `yarn release` task
> chore(smart-contracts): remove `semver` lib

- backend/ponder.schema.ts
- backend/src/handlers/RelayPoolFactory/PoolDeployed.ts
This PR fixes a bug in the `PoolDeployed` event handler where pools were incorrectly assigned the third party’s name and symbol instead of their own. The fix ensures that both standard pools and yield pools use the right identifiers upon deployment.
> fix(backend): Fix pool name and symbol assignment

- backend/ponder.schema.ts
- backend/src/handlers/RelayBridge/BridgeInitiated.ts
- backend/src/handlers/RelayPool/Deposit.ts
- backend/src/handlers/RelayPool/Withdraw.ts
- backend/src/handlers/RelayPoolFactory/PoolDeployed.ts
- package.json
This PR removes all references to totalAssets and shares in the yield pool, as they are not relevant. Additionally, it refactors our monorepo build script to improve build times.
> fix(backend): Remove irrelevant references and optimize monorepo build

- backend/ponder.config.ts
- backend/ponder.schema.ts
- backend/src/intervals/VaultSnapshot.ts
This PR introduces a handler that captures periodic share price snapshots for pools at configured block intervals, enabling time-series analysis of a vault's performance. The snapshot interval is configurable via `ponder.config.ts`.
```graphql
query GetPoolDetails($poolAddress: String!) {
relayPool(contractAddress: $poolAddress) {
yieldPool
contractAddress
chainId
asset
totalAssets
totalShares
outstandingDebt
snapshots(limit: 10, orderBy: "blockNumber", orderDirection: "desc") {
items {
vault
blockNumber
timestamp
sharePrice
}
}
origins(limit: 10) {
totalCount
items {
proxyBridge
originChainId
originBridge
maxDebt
}
}
}
}
```
> feature(backend): `VaultSnapshot`

- backend/src/handlers/RelayPool/LoanEmitted.ts
This PR introduces graceful handling of `LoanEmitted` events to prevent indexing failures when a corresponding `bridge_transaction` record is missing.
> fix(backend): Graceful handling of `LoanEmitted` events

- smart-contracts/ignition/modules/RelayPoolFactoryModule.ts
- smart-contracts/ignition/modules/TimelockTemplateModule.ts
- smart-contracts/test/RelayPool/inflation-attack.hardhat.ts
- smart-contracts/test/RelayPoolFactory/initialization.hardhat.ts
To avoid mistakes, makes the timelock template part of the pool factory deployment
> feat(smart-contracts): timelock template deployment

- backend/ponder.schema.ts
We were missing an important mapping on the chain id as well!
> fixing origin mapping to pool to include chainId

- smart-contracts/hardhat.config.ts
fixes current CI failure for zksync tests because of outdated default anvil version
> specify zksyncAnvil version

- packages/networks/src/networks/abstract.ts
- packages/networks/src/networks/ancient8.ts
- packages/networks/src/networks/base.ts
- packages/networks/src/networks/baseSepolia.ts
- packages/networks/src/networks/bob.ts
- packages/networks/src/networks/cyber.ts
- packages/networks/src/networks/hemi.ts
- packages/networks/src/networks/lisk.ts
- packages/networks/src/networks/mint.ts
- packages/networks/src/networks/optimism.ts
- packages/networks/src/networks/redstone.ts
- packages/networks/src/networks/soneium.ts
- packages/networks/src/networks/swell.ts
- packages/networks/src/networks/zero.ts
- packages/networks/src/networks/zksync.ts
- packages/networks/src/networks/zora.ts
- packages/types/src/types/networks.ts
It appears the `optimism-alt` is loosely default rn and we may need a better way or even a better name
> modify networks type to add required contract for checking chain status

- backend/ponder.config.ts
This should be indexing faster by not crawling networks for which we don't have an earliest block yet.
> feat: using latest when earliest block is not defined

- backend/ponder.schema.ts
- backend/src/handlers/OPPortal/WithdrawalProven.ts
- backend/src/handlers/RelayBridge/BridgeInitiated.ts
- backend/src/handlers/RelayPool/LoanEmitted.ts
- claimer/main.ts
- claimer/src/finalize-withdrawals.ts
- claimer/src/prove-transactions.ts
This new status should let us distinguish cases where the bridge has been `INITIATED` from the ones where the funds have been dispersed on the vault (`HANDLED`). 
We are now proving or finalizing calls that are `HANDLED` only so we should reduce the likeliness of a a "native" bridge resolving before an hyperlane message (we would only try to prove tx that have been handled)
> feat: adding a new status for better processing

- claimer/src/check-pending-bridges.ts
We should create an alarm in datadog for this in order to detect any transaction that was not quickly processed on the pool.
> adding a check for pending transactions that need to be handled

- backend/bin/log-format.sh
- backend/package.json
use `SERVICE_NAME` env when parsing json logs to be consistent with deployment process
> cleaner log parsing

- backend/src/handlers/RelayPool/OriginDisabled.ts
We should not delete origins when they are disabled since there could still be pending bridges that resolve (and events that are triggered!)
> fix(backend): not deleting disabled origins

- backend/src/handlers/OPPortal/WithdrawalFinalized.ts
This will make sure the `Lisk` tx is marked as FINALIZED.
We now have a strict order:
- `INITIATED`
- `HANDLED`
- `PROVEN` (we won't trigger proofs for tx that are not `HANDLED`)
- `FINALIZED` (by definition this must happen after a tx has been `PROVEN`)
> not requiring the state to be PROVEN

- packages/client/package.json
- packages/client/scripts/test.js
- packages/client/tsconfig.build.json
- packages/client/vite.config.ts
- yarn.lock
will bundle deps and avoid `ERR_REQUIRE_ESM` in cjs as `graphql-request` is esm only
> client: use vite to build ems/cjs 

- backend/package.json
the backend server relies on a stable db view to fetch data so we can be up even if the indexer is down
> backend: avoid http server downtime by serving pg view

- smart-contracts/contracts/BridgeProxy/deposit/ArbitrumOrbitNativeDepositBridgeProxy.sol
- smart-contracts/test/BridgeProxy/deposit/ArbitrumOrbitNativeDepositBridgeProxy.ethereum.ts
The function mistakenly used `gasParams` to pass Arbitrum retryable ticket gas limit - which is reserved for `transaction.txParams` object. This PR fixes it
> pass Arbitrum gas params on L1>L2 proxy bridge deposit
